apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/name: cmclasifier
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/cmclasifier
  newTag: e28d890378e58ee0035b2b4749b7fb0ba541e509
