apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/name: cmclasifier
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/cmclasifier
  newTag: 5ec0408ec896ffa9236b17c5a0456fc727c529a1
