apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/name: cmclasifier
  app.kubernetes.io/part-of: gihp4c

images:
- name: test
  newName: ghcr.io/herfel97/cmclasifier
  newTag: e1a2049ce9882732576d4ebf599629cced1f5b73
